services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: transcribeai-frontend
    ports:
      - "8080:80"
    environment:
      REACT_APP_API_KEY: "${REACT_APP_API_KEY}"
      REACT_APP_MAX_SIZE_AUDIO_BATCH: "${REACT_APP_MAX_SIZE_AUDIO_BATCH}"
      REACT_APP_MAX_TIME_PROCESSING_BATCH: "${REACT_APP_MAX_TIME_PROCESSING_BATCH}"
      REACT_APP_TIME_BETWEEN_EACH_POLLING_BATCH: "${REACT_APP_TIME_BETWEEN_EACH_POLLING_BATCH}"
      REACT_APP_MAX_SIZE_AUDIO_DIARIZATION: "${REACT_APP_MAX_SIZE_AUDIO_DIARIZATION}"
      REACT_APP_MAX_TIME_PROCESSING_DIARIZATION: "${REACT_APP_MAX_TIME_PROCESSING_DIARIZATION}"
      REACT_APP_TIME_BETWEEN_EACH_POLLING_DIARIZATION: "${REACT_APP_TIME_BETWEEN_EACH_POLLING_DIARIZATION}"
      REACT_APP_MAX_SPEAKERS_DIARIZATION: "${REACT_APP_MAX_SPEAKERS_DIARIZATION}"
    volumes:
      - ./volumes/assets:/usr/share/nginx/html/assets:ro
    restart: unless-stopped
